package work.tomosse.mses.model.db;

import java.util.Date;

public class AccessLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.id
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.msns_id
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    private Long msnsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.username
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.login_time
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.logout_time
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    private Date logoutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.created_at
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.updated_at
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.id
     *
     * @return the value of access_log.id
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.id
     *
     * @param id the value for access_log.id
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.msns_id
     *
     * @return the value of access_log.msns_id
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public Long getMsnsId() {
        return msnsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.msns_id
     *
     * @param msnsId the value for access_log.msns_id
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public void setMsnsId(Long msnsId) {
        this.msnsId = msnsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.username
     *
     * @return the value of access_log.username
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.username
     *
     * @param username the value for access_log.username
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.login_time
     *
     * @return the value of access_log.login_time
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.login_time
     *
     * @param loginTime the value for access_log.login_time
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.logout_time
     *
     * @return the value of access_log.logout_time
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.logout_time
     *
     * @param logoutTime the value for access_log.logout_time
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.created_at
     *
     * @return the value of access_log.created_at
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.created_at
     *
     * @param createdAt the value for access_log.created_at
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.updated_at
     *
     * @return the value of access_log.updated_at
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.updated_at
     *
     * @param updatedAt the value for access_log.updated_at
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}