package work.tomosse.mses.model.db;

import java.util.Date;

public class AccountMsns {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_msns.id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_msns.account_id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_msns.msns_id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    private Long msnsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_msns.created_at
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_msns.updated_at
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_msns.id
     *
     * @return the value of account_msns.id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_msns.id
     *
     * @param id the value for account_msns.id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_msns.account_id
     *
     * @return the value of account_msns.account_id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_msns.account_id
     *
     * @param accountId the value for account_msns.account_id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_msns.msns_id
     *
     * @return the value of account_msns.msns_id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public Long getMsnsId() {
        return msnsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_msns.msns_id
     *
     * @param msnsId the value for account_msns.msns_id
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public void setMsnsId(Long msnsId) {
        this.msnsId = msnsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_msns.created_at
     *
     * @return the value of account_msns.created_at
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_msns.created_at
     *
     * @param createdAt the value for account_msns.created_at
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_msns.updated_at
     *
     * @return the value of account_msns.updated_at
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_msns.updated_at
     *
     * @param updatedAt the value for account_msns.updated_at
     *
     * @mbg.generated Wed Feb 26 04:10:27 JST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}