version: "3"

services:
  app:
    networks:
      - app-net
    ports:
      - "18080:8080"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
  db:
    networks:
      - app-net
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    env_file: .env
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  app-net:
    driver: bridge
