version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - app-net
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: mysql:8.0
    networks:
      - app-net
    env_file: .env
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
networks:
  app-net:
    driver: bridge
