package work.tomosse.mses.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import work.tomosse.mses.model.db.AccessLog;
import work.tomosse.mses.model.db.AccessLogExample;

public interface AccessLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    long countByExample(AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int deleteByExample(AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int insert(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int insertSelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    List<AccessLog> selectByExample(AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    AccessLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int updateByExampleSelective(@Param("record") AccessLog record, @Param("example") AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int updateByExample(@Param("record") AccessLog record, @Param("example") AccessLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int updateByPrimaryKeySelective(AccessLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table access_log
     *
     * @mbg.generated Thu Mar 19 04:57:15 JST 2020
     */
    int updateByPrimaryKey(AccessLog record);
}