package work.tomosse.mses.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import work.tomosse.mses.model.db.AccountMsns;
import work.tomosse.mses.model.db.AccountMsnsExample;

@Mapper
public interface AccountMsnsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	long countByExample(AccountMsnsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int deleteByExample(AccountMsnsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int insert(AccountMsns record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int insertSelective(AccountMsns record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	List<AccountMsns> selectByExample(AccountMsnsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	AccountMsns selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int updateByExampleSelective(@Param("record") AccountMsns record, @Param("example") AccountMsnsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int updateByExample(@Param("record") AccountMsns record, @Param("example") AccountMsnsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int updateByPrimaryKeySelective(AccountMsns record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_msns
	 * @mbg.generated  Thu Mar 19 04:57:15 JST 2020
	 */
	int updateByPrimaryKey(AccountMsns record);
}