CREATE TABLE IF NOT EXISTS `access_log` (
    `id` BIGINT AUTO_INCREMENT,
    `msns_id` BIGINT NOT NULL,
    `username` VARCHAR(256) NOT NULL,
    `login_time` TIMESTAMP NOT NULL,
    `logout_time` TIMESTAMP NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`msns_id`) REFERENCES msns(`id`)
);